### ISSUE TITLE
Upgrading the API to Python 3.7.3

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#14]
In GitLab by @ggcr on Nov 10, 2022, 08:28

Hi folks,

Because the configparser is Python 3.7.3 and we are using Python 2.8 at the API, after the current release it would be a great idea to catch up with AS4 and update the API to **Python 3.7.3**.

It should not be a hard process because there was a successful attempt to port the API some years ago. And we also had a successful port of Autosubmit.

For reference I think we should follow the steps made by the previous ports:

* [How Willmer ported the API](https://earth.bsc.es/gitlab/es/autosubmit/-/issues/446)

* [How @dbeltrankyl ported Autosubmit](https://earth.bsc.es/gitlab/es/autosubmit/-/issues/446#note_64423)

For more information there is this [post](https://docs.python.org/3.7/howto/pyporting.html) on Python docs about the methodology to follow to run a successful upgrade.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 10, 2022, 08:29

I have started playing a bit and I created my own env in my local machine, applied 2to3 and from what I've seen the whole API was modified so that the day it had to be upgraded to Python 3 it was an easy step. 

So yeah, by the looks of it I don't think it should take a lot of time, there is a lot of progress already done.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 14, 2022, 13:03

I already deployed an initial version that has fixed dependencies. Located at `/home/rocky/development/AS_API_3/autosubmit_api` and has to be run with the Virtual Env at `/var/www/html/autosubmitapi3/venv37/bin/activate`.

```
// exit if you are in root mode
[root@vm development]# exit
exit
[rocky@vm ~]$ 

[rocky@vm ~]$ source /var/www/html/autosubmitapi3/venv37/bin/activate
[rocky@vm ~]$ cd /home/rocky/development/AS_API_3/autosubmit_api
[rocky@vm ~]$ flask run
```

Couple changes that are not mentioned in the last attempts:

* **sqlite3** to be replaced by pysqlite3, therefore all the import statements need to be translated...

  `import sqlite3` => `import pysqlite3 as sqlite3`

**Note that this is just to be able to simply execute the API; I still don't know if it works whether well or not.**

* In order to run **gunicorn** we need to change the PATH:
  ```
  [root@vm rocky]# export PYTHONHOME=/usr/local
  [root@vm rocky]# export PATH=$PATH:/usr/local/bin
  [root@vm rocky]# gunicorn
  ^C
  [root@vm rocky]# bash /home/rocky/development/AS_API_3/autosubmit_api/AS_API_3_update.sh
  [root@vm rocky]# ...
  [root@vm rocky]# Gunicorn starting in 3 seconds...
  [root@vm rocky]# /home/rocky/development/logs/202211141514logunicorn.txt
  ```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 14, 2022, 15:17

I've modified the .bashrc to include:

`export PYTHONHOME=/usr/local`: For detecting the python pip libs

`export PATH=$PATH:/usr/local/bin`: To run gunicorn in root (and not only on normal user)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Nov 14, 2022, 16:41

Good progress by now @ggcr.

Whether it just runs or "runs well" makes me wonder if now that you are familiar with the API, it would also be the right time to start introducing some automated tests as we have in Autosubmit (https://earth.bsc.es/gitlab/es/autosubmit/tests) and using the CI pipeline.

However, we should first have a conversation about the status of the tests in Autosubmit (@dbeltrankyl @ jberlin @kinow). We can talk about it in the next weekly meeting.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 21, 2022, 13:50

Small update, I will annotate all the steps I am following in order to do not forget and possible feedback.


**CREATE AND VALIDATE NEW ENV**

```
ssh rocky@bscesautosubmitdev01.bsc.es

# 1. as root
sudo su

# 2. append your preferred paths to your .bash_profile
echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bash_profile 
echo 'export PYTHONHOME=/usr/local' >> ~/.bash_profile 

# 3. create virtual env (if there isn't one already created)
cd /var/www/html/
python3.7 -m virtualenv <ENV_NAME>

# 4. activate venv
source /var/www/html/<ENV_NAME>/bin/activate

# 5. install requirements using python3.7
export PYTHONHOME=/usr/local
python -m pip install -r /var/www/html/requirements.txt

# 6. run gunicorn
cd /home/rocky/development
/var/www/html/<ENV_NAME>/bin/gunicorn --error-logfile /home/rocky/development/logs/AS_API_3_tmp_log --timeout 600 -b 0.0.0.0:8081 -w 4 AS_API_3.autosubmit_api.app:app --daemon --preload
```

**RUN ENV**

I've made a script to kill the current instance and run another one, similar to what we had before.

**/home/rocky/development/update_launch_autosubmit_API_3.sh**

```
sudo su

cd /home/rocky/development
bash update_launch_autosubmit_API_3.sh
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Nov 22, 2022, 15:29

>and possible feedback.

I don't have a lot of context about the API, so I am sorry if I say anything that was already answered/decided previously :thumbsup: 

>#add the following into the activate script at the bottom:
>#`export PYTHONHOME=/usr/local` and `export PATH=$PATH:/usr/local/bin`


I think these should go in a bash profile, as the `activate` script is generated when creating the virtual environment.

>#5. install the API as package to allow absolute imports
>python -m pip install --editable .

Won't we release it to PYPI? If so, I think this step could be replaced by `pip install autosubmit-...`

Everything else sounds good, and it's well written and easy to understand and follow (i.e. this is the sort of documentation I wouldn't mind being handed over if someone was going on holidays and asked me to run on an environment :slight_smile: )

-Bruno

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 23, 2022, 12:11

Thanks for taking your time to read it Bruno!

> Won't we release it to PYPI? If so, I think this step could be replaced by `pip install autosubmit-...`

Yes, the idea is to upload it to PyPi once we have it working in Python3.

> I think these should go in a bash profile, as the `activate` script is generated when creating the virtual environment.

You are right. This is way better than having to modify the virtualenv shell scripts.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 23, 2022, 12:18

A little follow-up on what I've been doing:

**Problem while generating the token**: `module 'jwt' has no attribute 'encode'`

Actually this weird "bug" had me going crazy. I still don't know how I fixed it.

Turns out that there are two main JWT libs in the Python Community. JWT and PyJWT, and I don't know why but they share the same name space, and therefore both are imported as "jwt". 

It was a **version conflict**. I tried a bunch of times to install and uninstall PyJWT, jwt, Flask etc until it worked.

**Problem while generating the tree, graph, quick view...**

The tree wasn't reading the joblist right and it's because in Python 3, pickle needs an `encoding` parameter.

`pickle.load(openFile) => pickle.load(openFile, encoding="latin1")`

Also, the pkl file had to be opened as a binary ('rb').

---

**TO-DO API:**

- [x] Authentication
- [x] Current Active Experiments
- [x] Tree
- [x] Graph
- [x] Other views
- [x] Summaries
- [x] Shutdown

**TO-DO API other:**
- [x] Move the exports of PYTHONHOME, PATH and os env variables to .bash_profile
- [x] Enforce encoding to UTF-8
- [x] Update step by step on "How to create env" and "How to run".
- [x] Create a new `update` script.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Nov 23, 2022, 12:41

Hello @ggcr ,

> `pickle.load(openFile) => pickle.load(openFile, encoding="latin1")`

about the encoding, I think that the pickle of python 3 doesn't necessarily needs the encoding is just that your default locale has an incompatible locale with the saved one of the joblist.

 you can set a default locale for the whole code by using the locale lib. 

With the code as follows I set all AS-related tasks to use the UTF8:

`import locale`

```
# Enforce LANG=UTF-8
        try:
            try:
                locale.setlocale(locale.LC_ALL, 'C.UTF-8')
            except Exception as e:
                try:
                    locale.setlocale(locale.LC_ALL, 'C.utf8')
                except Exception as e:
                    try:
                        locale.setlocale(locale.LC_ALL, 'en_GB')
                    except Exception as e:
                        locale.setlocale(locale.LC_ALL, 'es_ES')
        except Exception as e:
            Log.info("Locale C.utf8 is not found, using '{0}' as fallback".format("C"))
            locale.setlocale(locale.LC_ALL, 'C')
```

About the code itself, there is a list of available encoding that AS can look to instead of using try: except, but In my experience, even if it is listed there it can still not work ( happened with bscautosubmit01)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Nov 23, 2022, 12:46

Hi @ggcr ,

Another thing, I worked with Albert to deploy Autosubmit 4 in the new hub. This new hub is using python 3.9.6 so maybe we should also test the API with that version.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 23, 2022, 13:10

Thanks a lot Dani, I will try to encapsulate it into a method and simply call it. Way better than having to change all the pickle loads calls.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 23, 2022, 13:11

Yeah sure!

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Nov 23, 2022, 13:51

Good idea @dbeltrankyl

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Nov 28, 2022, 12:45

unassigned @ggcr

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 1, 2022, 10:08

I had problems with retrocompatibility for experiments with AS_VERSION < 3.13. **Fixed now**. Validation pending.

---

Some problems with sorted functions.

**Before (Python 2)**
```
date_member_groups[(key, member)] = sorted(
     local_list, key=lambda x: x.chunk)
```
`>>> 1 < None   => False`

**Now (Python 3.7.3)**
```
date_member_groups[(key, member)] = sorted(
     local_list, key=lambda x: x.chunk if x.chunk is not None else 0)
```
`>>> 1 < None   => Error`

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Dec 1, 2022, 10:43

@ggcr to create an issue to document the workers and verify their status (if they are useful at this point) and if they continue working well after the upgrade

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 1, 2022, 11:56

marked this issue as related to #15

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 1, 2022, 11:56

marked this issue as related to #12

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jan 19, 2023, 17:43

Hi @ggcr , please prepare the branch where the migration to Python 3.7.3 took place (I guess `AS_API_PYTHON3` right) for merging into the master branch, I tested the current version deployed in development and seems to work properly. thanks!

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jan 19, 2023, 18:07

Also please remove those folders (I guess venvs) that are no longer used in the Development VM:

```
ll -lrt  /var/www/html/
total 4
drwxr-xr-x. 3 root root  35 abr  8  2022 autosubmitapi
drwxr-xr-x  3 root root  20 nov 14 12:17 autosubmitapi3
drwxr-xr-x  6 root root  88 nov 28 08:13 AS_API_3
drwxr-xr-x  6 root root  88 nov 28 08:43 TEST_API_3
-rw-r--r--  1 root root 840 nov 28 08:43 requirements.txt
drwxr-xr-x  6 root root  88 nov 28 08:45 Autosubmit_API_3
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Jan 24, 2023, 08:10

@ jberlin perfect, I will check for the commits of new features that were not propagated into the Python 3 branch and remove the unused envs.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Jan 26, 2023, 11:37

@ jberlin 

The other branch left `AS_API_HOTFIX` can be deleted, this branch was for the fixes of bugs that I was already doing in the API Python 3 branch but for the Python 2 API. So they are already at master and it can be removed.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jan 26, 2023, 11:48

Thanks @ggcr , I will remove it then

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 22, 2023, 17:45

unassigned @ggcr

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 22, 2023, 17:46

The new version with the migration was deployed several weeks ago.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on May 12, 2023, 18:13

mentioned in issue testing_suite#33
